spring:
  redis:
    host: ${app.redis.host}
    port: ${app.redis.port:6379}
    password: ${app.redis.password}
    # 缓存过期时间(单位:秒)
    default-expiration: ${app.redis.default-expiration:1800}
    jedis:
      pool:
        # 连接池最大阻塞等待时间(负值表示没有限制) 默认 -1
        max-wait: ${app.redis.jedis.pool.max-wait:-1}
        # 连接池最大连接数(负值表示没有限制) 默认 8
        max-active: ${app.redis.jedis.pool.max-active:300}
        # 连接池中的最大空闲连接 默认 8
        max-idle: ${app.redis.jedis.pool.max-idle:40}
        # 连接池中的最小空闲连接 默认 0
        min-idle: ${app.redis.jedis.pool.min-idle:0}
    database: ${app.redis.database:0}