spring:
  redis:
    host: ${app.redis.host}
    port: ${app.redis.port:6379}
    password: ${app.redis.password}
    cluster:
      nodes:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0