spring:
  redis:
    password: ${app.redis.password}
    timeout: 60000
    # 缓存过期时间(单位:秒)
    default-expiration: ${app.redis.default-expiration:1800}
    sentinel:
      master: mymaster
      master-onlyWrite: true
      fail-max: 3
      nodes: ${app.redis.nodes}
    jedis:
      pool:
        max-wait: -1
        max-active: 300
        max-idle: 100
        min-idle: 20
    database: ${app.redis.database:0}