
logging:
  level:
    org.springframework: info
    cn.com.siss: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(---){faint} %clr(%-80.80logger{79}){cyan} %clr(:){faint} %m%n%wEx"
  config: classpath:logback-spring.xml

---

spring:
  profiles: local

logging:
  level:
    cn.com.siss: debug

---

spring:
  profiles: prod

logging:
  level:
    cn.com.siss: warn