
logging:
  level:
    org.springframework: info
    cn.com.siss: info
  config: classpath:logback-spring.xml
  pattern:
    console: '%d{YYYY-MM-dd HH:mm:ss.SSS} ${PID} [%-25.25thread] %highlight(%-5level)  %green(%-40.40logger{39}) : %msg%n'
---

spring:
  profiles: local

logging:
  level:
    cn.com.siss: debug

---

spring:
  profiles: prod

logging:
  level:
    cn.com.siss: warn