spring:
  # 数据库配置
  datasource:
    # 数据库名称
    name: ${app.datasource.name}
    # DRUID数据库连接池类别
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接URL
    url: jdbc:mysql://${app.datasource.host:mysql-${spring.profiles.active}}:${app.datasource.port:3306}/${app.datasource.name}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: ${app.datasource.username}
    password: ${app.datasource.password}
    # 驱动类名称
    driverClassName: com.mysql.jdbc.Driver
    # 初始化时建立物理连接的个数
    initialSize: 1
    # 最小连接数
    minIdle: 1
    # 最大连接数
    maxActive: 20
    # 最大连接等待时间
    maxWait: 60000
    # 关闭空闲连接间隔时间
    timeBetweenEvictionRunsMillis: 60000
    # 空闲保持连接时间
    minEvictableIdleTimeMillis: 300000
    # 空闲时是否检测连接
    testWhileIdle: true
    # 申请连接时检测连接(开启配置会降低性能)
    testOnBorrow: false
    # 归还连接时检测连接(开启配置会降低性能)
    testOnReturn: false
    # 检测连接是否可用的SQL语句
    validationQuery: SELECT 'x' FROM DUAL
    # 开启强制关闭连接(检测连接池泄露)
    removeAbandoned: true
    # 连接强制关闭时间
    removeAbandonedTimeout: 1800
    # 输出强制关闭连接日志
    logAbandoned: true
    # 滤波器配置 encrypt password
    filters: config,stat,wall,log4j
    # DRUID连接属性字符串
    connectionProperties: "config.decrypt=true;config.decrypt.key=${app.datasource.druid.public-key};druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
    # 是否缓存PSCache
    poolPreparedStatements: false
    # 启用缓存最大值
    maxOpenPreparedStatements: 20
    # 合并监控数据源的数据
    useGlobalDataSourceStat: true

  # 主数据源名称; 无数据源名称则不需要配置, 如果配置了dynamicDataBase则必须配置, 名称必须为dynamicDataBase的数据源名的其中一个
  # mainDatabase: master
  # 多数据源的数据源名称与独自的配置信息
  # dynamicDataBase:
    # master:
      # url: jdbc:mysql://${app.datasource.host}/${app.datasource.name}?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    # slave:
      # url: jdbc:mysql://${app.datasource.host}/${app.datasource.name}_1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false

# druid monitor 配置
druid:
  wiki:
    # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
    webStatFilter:
      enabled: true #是否启用StatFilter默认值true
      urlPattern: "/*"
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid2/*"
      sessionStatEnable:
      sessionStatMaxCount:
      principalSessionName:
      principalCookieName:
      profileEnable:
    # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
    statViewServlet:
      enabled: true #是否启用StatViewServlet默认值true
      urlPattern: "/druid/*"
      resetEnable: false
      loginUsername: siss
      loginPassword: siss.pub
      allow: ""
      deny: ""
